### ISSUE TITLE
No token found after adding a token

### ISSUE THREAD

**Issue by brianorwhatever** [fatihacet/gitlab-workflow#1]
I add a token as instructed but I don't get any confirmation it succeeded.
when I try to do a command

> GitLab Workflow: Cannot make request. No token found.

**Comment by duwke** [comment]
Same.  I am trying to connect to our local instance of gitlab.  I'm not sure if that is causing the issue.

**Comment by duwke** [comment]
Oh.. if I set the gitlab.instanceUrl in preferences, it works.

**Comment by gmaggess** [comment]
I have a company hosted gitlab instance. I don't see any errors in the UI, but I don't see any data either. Any help is appreciated.

**Comment by mrca** [comment]
How to a

> Oh.. if I set the gitlab.instanceUrl in preferences, it works.

How to do this actually?

**Comment by vr001** [comment]
+1. Trying to our company hosted gitlab instance. 
Even tried setting Preferences -> Settings -> gitlab.instanceUrl, but getting 
_**cannot make request.
Failed to validate CI configuration.**_
Not sure whether i am missing something.

**Comment by jakdept** [comment]
@mrca To set `gitlab.instanceUrl` in preferences, if on macOS with VSCode open, hit `⌘` + `,` and enter it there - that's JSON. Or, if not on macOS, hit `ctrl` + `p` and type in `preferences` until you see `Preferences: Open Settings (JSON)` and select that one. It gets you to the same place - so put it in there.

Do note that your VSCode settings file, you can put a lot of goodies in there.

@vr001 Your issue is not with connecting to your corporate gitlab instance, you are connected. Validation of your `.gitlab-ci.yml` happens on the Gitlab instance. Instead, your `.gitlab-ci.yml` in your editor is invalid - it's being pushed to the server to be tested directly, and then it's got errors.

If you cannot determine what's wrong (it sometimes throws me off too) commit it, push it to GitLab, and open it up on that branch in the file viewer - there's a GitLab CI validator built in that gives much better output.

**Comment by fatihacet** [comment]
Sorry folks for missing the issues here in GitHub. This repo is just a mirror of the original repo hosted and maintained in GitLab which makes sense since it's an extension for GitLab 🙂 

I really don't understand why GitHub doesn't let me know about the issues on my own repo. I have to go and change the notification settings to Watching explicitly. It's just weird. 

Being said that, I will close this issue since it's a misconfiguration of the extension. Please take a look at the closed issues labeled with "token issue". They can be found [here](https://gitlab.com/fatihacet/gitlab-vscode-extension/issues?scope=all&utf8=%E2%9C%93&state=closed&label_name[]=token-issue).
